spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: postgres
  jpa:
    hibernate:
      # 自动创建表
      ddl-auto: update
    show-sql: true

# pg方言，需要配置，否则会出现org.hibernate.type.SerializationException: could not deserialize
spring.jpa.database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect