server:
  port: 9000


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poi_test?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: 123456
  jpa:
    hibernate:
      # 自动创建表
      ddl-auto: update
#    show-sql: true
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB

# pg方言，需要配置，否则会出现org.hibernate.type.SerializationException: could not deserialize
spring.jpa.database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect