server:
  port: 9010

spring:
  elasticsearch:
    uris: https://192.168.20.152:9200
#    password: b3M*r6f3bs+qAmsRTlAu
    username: elastic
    password: 123456
  #    password: buWFYsXinLs0ElvZ47UB
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
