server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 100MB

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db
    druid:
      max-active: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  boot:
    admin:
      ## admin 服务端访问地址
      context-path: /admin
      ## admin 客户端连接服务端
      client:
        # 为了显示客户端的ip否则是以主机名显示的，这样需要添加hosts影射。
        url: http://localhost:${server.port}${spring.boot.admin.context-path}
        instance:
          prefer-ip: true
          name: gear-sqlite



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
