spring:
  servlet:
    multipart:
      max-file-size: 100MB

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db
    druid:
      max-active: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

