server:
  port: 3000

spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 100MB
      file-size-threshold: 20MB
file:
  chunk:
    record-save-type: memory
    upload-dir: ./uploadData/
